# Generated by Django 3.1.5 on 2021-02-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_userprofile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow',
            new_name='follower',
        ),
    ]
